### ISSUE TITLE
Exception on startup of project

### ISSUE THREAD

**Issue by uzername** [anycad/anycad.rapid.net.sample#8]
Hello. I have cloned this project, now I am trying to build it and run.

It builds fine, but I get such exception on startup:

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'AnyCAD.Foundation.AnyCADPINVOKE' threw an exception.
  Source=AnyCAD.Foundation.Net
  StackTrace:
   at AnyCAD.Foundation.AnyCADPINVOKE.ModelingEngine_Initialize()
   at AnyCAD.Foundation.GlobalInstance.Initialize()
   at AnyCAD.Demo.Program.Main() in 
  \AnyCAD.WinForms\Program.cs:line 18

Inner Exception 1:
TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.

Inner Exception 2:
DllNotFoundException: Unable to load DLL 'AnyCAD.Foundation.NetHost.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

**Comment by uzername** [comment]
I created a starting project as explained here: http://www.opencascade.net/guide/guide-00-project-settings.html

I was able to build it fine.

Then I copied folders `\x86` and `\x64` to folder `\anycad.rapid.net.sample\bin\Debug` . It worked

**Comment by anycad** [comment]
we recommend to use nuget to manage the SDK :)
